const API="/api";
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
let state={user:null,teams:[],incidents:[],sensors:[],dispatches:[],map:null,mapLayers:[],charts:{},mapData:null};
const disasterTypes=["Flood","Earthquake","Cyclone","Fire","Landslide","Tsunami","Heatwave","Drought","Industrial Accident","Gas Leak","Chemical Hazard","Building Collapse","Other"];

function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function ago(v){const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));return m<1?"just now":m<60?m+" min ago":m<1440?Math.floor(m/60)+" hr ago":Math.floor(m/1440)+" d ago";}
function fmt(v){return new Date(v).toLocaleString([], {day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});}
async function api(path,opts={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(opts.headers||{})},...opts});if(r.status===401){location.href="/login?next="+encodeURIComponent(location.pathname+location.hash);throw new Error("Authentication required.");}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d;}
function text(id,v){const e=$(id);if(e)e.textContent=v;}
function msg(v,good=false){const e=$("#formMessage");e.textContent=v;e.className="form-message "+(good?"success":"error");}
function riskClass(v){return String(v||"").toLowerCase().replace(" ","-");}

async function loadUser(){const d=await api("/me");if(!d.signedIn){$("#authGate").classList.add("show");return false;}state.user=d.user;text("#userName",d.user.name);text("#userRole",d.user.role+" · authenticated");text("#avatar",(d.user.name||"U")[0].toUpperCase());return true;}
async function loadDashboard(){const d=await api("/dashboard");text("#activeIncidents",String(d.active_incidents).padStart(2,"0"));text("#criticalIncidents",d.critical_incidents);text("#sensorCount",d.sensors_online);text("#teamCount",d.available_teams);text("#dispatchCount",d.active_dispatches+" active missions");text("#alertCount",d.active_alerts);text("#navIncidentCount",d.active_incidents);text("#navAlertCount",d.active_alerts);text("#riskScoreKpi",d.risk.score);text("#riskLevelKpi",d.risk.level+" risk");text("#lastUpdated","Updated "+new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}));}
async function loadIncidents(){const d=await api("/incidents");state.incidents=d.incidents;text("#queueCount",d.incidents.length);$("#incidentList").innerHTML=d.incidents.length?d.incidents.map(x=>`<article class="incident ${x.severity.toLowerCase()}"><div class="severity-dot"></div><div class="incident-main"><b>${esc(x.title)}</b><span>${esc(x.disaster_type)} · ${esc(x.location)} · ${ago(x.created_at)}</span></div><span class="severity-label">${esc(x.status)}</span><button class="resolve-btn" data-incident="${x.id}">${x.status==="RESOLVED"?"Reopen":"Update"}</button></article>`).join(""):"<div class='empty'>No incidents recorded.</div>";$$("[data-incident]").forEach(b=>b.onclick=()=>openIncidentDetails(b.dataset.incident));}
async function openIncidentDetails(id){const d=await api("/incidents/"+id);const i=d.incident;openModal("incident");$("#fTitle").value=i.title;$("#fType").value=i.disaster_type;$("#fSeverity").value=i.severity;$("#fLocation").value=i.location;$("#fDescription").value=i.description||"";$("#fLat").value=i.latitude??"";$("#fLng").value=i.longitude??"";$("#modalTitle").textContent="Incident details";$("#submitModal").textContent=i.status==="RESOLVED"?"Reopen incident":"Move to response";$("#commandForm").dataset.editId=id;$("#commandForm").dataset.editStatus=i.status==="RESOLVED"?"ACTIVE":i.assigned_team?"RESOLVED":"UNDER RESPONSE";const timeline=d.timeline.map(x=>`<div class="timeline-item"><b>${esc(x.action)}</b><span>${esc(x.details||"Operational update")} · ${fmt(x.created_at)}</span></div>`).join("");$("#incidentFields").insertAdjacentHTML("beforeend",`<div class="timeline"><b>Incident timeline</b>${timeline||"<span>No audit events yet.</span>"}</div>`);}
function sensorStatus(x){return x.threshold_status==="CRITICAL"?"critical":x.threshold_status==="WARNING"?"warning":"normal";}
async function loadSensors(){const d=await api("/sensors");state.sensors=d.sensors;$("#sensorGrid").innerHTML=d.sensors.map(x=>`<div class="sensor-card"><div class="sensor-head"><div class="sensor-symbol">${x.category==="WATER"?"≈":x.category==="SMOKE"?"◌":x.category==="GAS"?"◈":"⌁"}</div><span class="sensor-status ${x.status.toLowerCase()}">${esc(x.status)}</span></div><span class="sensor-name">${esc(x.name)}</span><strong>${esc(x.value)} <small>${esc(x.unit)}</small></strong><div class="threshold-row"><span class="${sensorStatus(x)}">${esc(x.threshold_status)}</span><small>Warn ${x.threshold_warning??"—"} · Critical ${x.threshold_critical??"—"}</small></div><div class="sensor-bar"><i style="width:${Math.min(100,Math.max(5,Number(x.value)||5))}%"></i></div><div class="sensor-meta"><span>${esc(x.location)}</span><span>BAT ${esc(x.battery)}%</span></div><button class="sensor-edit" data-sensor="${x.id}">Adjust simulated value</button></div>`).join("");$$("[data-sensor]").forEach(b=>b.onclick=()=>openSensorModal(b.dataset.sensor));}
async function loadTeams(){const d=await api("/teams");state.teams=d.teams;$("#teamTable").innerHTML=d.teams.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.specialty)}</td><td>${esc(x.location)}</td><td>${x.members}</td><td><span class="team-status ${riskClass(x.status)}">${esc(x.status)}</span></td><td><select class="table-select team-update" data-team="${x.id}"><option value="">Change</option>${["AVAILABLE","DEPLOYED","EN ROUTE","OFFLINE"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("");$$(".team-update").forEach(s=>s.onchange=async()=>{if(!s.value)return;try{await api("/teams",{method:"PATCH",body:JSON.stringify({id:s.dataset.team,status:s.value})});await refresh();}catch(e){alert(e.message);}});}
async function loadDispatches(){const d=await api("/dispatches");state.dispatches=d.dispatches;$("#dispatchList").innerHTML=d.dispatches.length?d.dispatches.map(x=>`<div class="mission"><div class="mission-id">#${x.id.slice(0,6).toUpperCase()}</div><div><b>${esc(x.mission)}</b><span>${esc(x.destination)} · ${esc(x.team_name||"Unassigned")}</span></div><span class="mission-priority ${x.priority.toLowerCase()}">${esc(x.priority)}</span><select class="table-select dispatch-update" data-dispatch="${x.id}"><option>${esc(x.status)}</option>${["PENDING","ACTIVE","EN ROUTE","COMPLETED"].filter(s=>s!==x.status).map(s=>`<option>${s}</option>`).join("")}</select></div>`).join(""):"<div class='empty'>No dispatch missions created yet.</div>";$$(".dispatch-update").forEach(s=>s.onchange=async()=>{try{await api("/dispatches",{method:"PATCH",body:JSON.stringify({id:s.dataset.dispatch,status:s.value})});await refresh();}catch(e){alert(e.message);}});}
async function loadRisk(){const d=await api("/risk");text("#riskScoreValue",d.score);text("#riskLevelValue",d.level+" RISK");text("#riskDrivers",d.drivers.join(" · "));text("#riskWater",d.metrics.water);text("#riskVibration",d.metrics.vibration);text("#riskSmoke",d.metrics.smoke);text("#riskGas",d.metrics.gas);$("#riskGauge").style.width=d.score+"%";$("#riskGauge").className="risk-"+riskClass(d.level);}
async function loadAlerts(){const d=await api("/alerts");$("#alertGrid").innerHTML=d.alerts.length?d.alerts.map(a=>`<article class="alert-card ${a.severity.toLowerCase()}"><div><span class="alert-level">${esc(a.severity)}</span><h3>${esc(a.title)}</h3><p>${esc(a.message)}</p><small>⌖ ${esc(a.location)} · ${ago(a.created_at)}</small></div><div class="alert-action"><b>Recommended action</b><span>${esc(a.recommended_action)}</span><button class="resolve-btn" data-alert="${a.id}">Dismiss</button></div></article>`).join(""):"<div class='empty'>No active alerts.</div>";$$("[data-alert]").forEach(b=>b.onclick=async()=>{await api("/alerts/"+b.dataset.alert,{method:"PATCH",body:JSON.stringify({status:"DISMISSED"})});await refresh();});const critical=d.alerts.find(x=>x.severity==="CRITICAL");if(critical){$("#criticalBanner").classList.remove("hidden");text("#criticalBannerTitle",critical.title);text("#criticalBannerText",critical.message);}else $("#criticalBanner").classList.add("hidden");}
async function loadReports(){const days=Number($("#reportRange").value||30);const d=await api("/reports?days="+days);text("#reportIncidents",d.incidents_week);text("#reportAvg",d.avg_response_minutes+" ");text("#reportCompleted",d.missions_completed);text("#reportUtilization",d.resource_utilization+"%");drawChart("typeChart","bar","Incidents by disaster type",d.by_type);drawChart("severityChart","doughnut","Severity",d.by_severity);drawChart("timeChart","line","Incidents over time",d.over_time);return days;}
function drawChart(id,type,label,data){const canvas=$("#"+id);if(state.charts[id])state.charts[id].destroy();state.charts[id]=new Chart(canvas,{type,data:{labels:data.map(x=>x.name||x.label),datasets:[{label,data:data.map(x=>x.value),borderWidth:2,tension:.35}]},options:{responsive:true,plugins:{legend:{display:type==="doughnut"}},scales:type==="doughnut"?{}:{y:{beginAtZero:true,ticks:{precision:0}}}}});}
async function loadActivity(){const d=await api("/activity");$("#activityList").innerHTML=d.activity.length?d.activity.map(x=>`<div class="activity"><span class="activity-dot"></span><div><b>${esc(x.action)} · ${esc(x.entity)}</b><small>${esc(x.details||"Operational event")}</small></div><time>${ago(x.created_at)}</time></div>`).join(""):"<div class='empty'>Audit activity will appear here.</div>";}
async function loadAudit(){if(!["ADMIN","OPERATOR"].includes(state.user?.role)){$("#auditTable").innerHTML="<tr><td colspan='5'>Audit access is restricted.</td></tr>";return;}const d=await api("/audit");$("#auditTable").innerHTML=d.audit.map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.user_name||"System")}</td><td><b>${esc(x.action)}</b></td><td>${esc(x.entity)}</td><td>${esc(x.details||"—")}</td></tr>`).join("");}
async function loadGuides(){const d=await api("/preparedness");$("#guideGrid").innerHTML=d.guides.map(g=>`<article class="guide-card"><div class="guide-icon">✓</div><h3>${esc(g.title)}</h3><div><b>BEFORE</b><ul>${g.before_steps.map(s=>"<li>"+esc(s)+"</li>").join("")}</ul></div><div><b>DURING</b><ul>${g.during_steps.map(s=>"<li>"+esc(s)+"</li>").join("")}</ul></div><div><b>AFTER</b><ul>${g.after_steps.map(s=>"<li>"+esc(s)+"</li>").join("")}</ul></div></article>`).join("");}
async function loadContacts(){const d=await api("/emergency-services");$("#contactGrid").innerHTML=d.services.map(s=>`<article class="contact-card"><span class="contact-icon">☎</span><div><b>${esc(s.name)}</b><small>${esc(s.service_type)} · ${esc(s.location)}</small></div><strong>${esc(s.phone)}</strong></article>`).join("");}

function initMap(){state.map=L.map("liveMap").setView([28.6139,77.2090],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(state.map);state.map.on("zoomend",()=>{});}
function marker(lat,lng,html,className){const icon=L.divIcon({className:"custom-marker",html:`<div class="${className}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});return L.marker([lat,lng],{icon}).bindPopup(html);}
async function loadMap(){if(!state.map)initMap();const d=await api("/map");state.mapData=d;state.mapLayers.forEach(x=>x.remove());state.mapLayers=[];const filter=document.querySelector(".filter.active")?.dataset.map||"all";const add=(lat,lng,html,c)=>{const m=marker(lat,lng,html,c).addTo(state.map);state.mapLayers.push(m);};if(filter==="all"||filter==="incidents"||filter==="critical")d.incidents.forEach(x=>{if(filter==="critical"&&x.severity!=="CRITICAL")return;add(x.latitude,x.longitude,`<b>${esc(x.title)}</b><br>${esc(x.disaster_type)} · ${esc(x.severity)}<br>${esc(x.location)}`,x.severity==="CRITICAL"?"marker-critical":"marker-warning");});if(filter==="all"||filter==="teams")d.teams.forEach(x=>add(x.latitude,x.longitude,`<b>${esc(x.name)}</b><br>${esc(x.specialty)}<br>Status: ${esc(x.status)}`,"marker-team"));if(filter==="all"||filter==="sensors")d.sensors.forEach(x=>add(x.latitude,x.longitude,`<b>${esc(x.name)}</b><br>${esc(x.category)}: ${esc(x.value)} ${esc(x.unit)}<br>${esc(x.status)}`,"marker-sensor"));if(filter==="all")d.emergency_services.forEach(x=>add(x.latitude,x.longitude,`<b>${esc(x.name)}</b><br>${esc(x.service_type)} · ${esc(x.phone)}`,"marker-service"));setTimeout(()=>state.map.invalidateSize(),150);}
function openModal(mode){$("#modal").classList.add("open");$("#commandForm").reset();$("#commandForm").dataset.editId="";$("#commandForm").dataset.mode=mode;$("#incidentFields").hidden=mode!=="incident";$("#dispatchFields").hidden=mode!=="dispatch";$("#alertFields").hidden=mode!=="alert";$("#sensorFields").hidden=mode!=="sensor";$("#modalEyebrow").textContent=mode==="incident"?"INCIDENT COMMAND":mode==="dispatch"?"MISSION CONTROL":mode==="alert"?"PUBLIC SAFETY":"TELEMETRY LAB";$("#modalTitle").textContent=mode==="incident"?"Create incident":mode==="dispatch"?"Create mission":mode==="alert"?"Issue emergency alert":"Adjust simulated telemetry";$("#submitModal").textContent=mode==="incident"?"Create incident":mode==="dispatch"?"Create mission":mode==="alert"?"Issue alert":"Update sensor";$("#formMessage").textContent="";if(mode==="incident")populateTypes();if(mode==="dispatch")populateDispatch();if(mode==="alert"){$("#fAlertType").innerHTML=disasterTypes.map(x=>`<option>${x}</option>`).join("");}}
function closeModal(){$("#modal").classList.remove("open");$("#commandForm").reset();$("#incidentFields").querySelectorAll(".timeline").forEach(x=>x.remove());}
function populateTypes(){$("#fType").innerHTML=disasterTypes.map(x=>`<option>${x}</option>`).join("");}
function populateDispatch(){$("#fTeam").innerHTML=state.teams.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.status)}</option>`).join("");$("#fIncident").innerHTML='<option value="">No linked incident</option>'+state.incidents.filter(x=>x.status!=="RESOLVED").map(x=>`<option value="${x.id}">${esc(x.title)} · ${esc(x.location)}</option>`).join("");}
function openSensorModal(id){openModal("sensor");const s=state.sensors.find(x=>x.id===id);$("#fSensor").innerHTML=state.sensors.map(x=>`<option value="${x.id}" ${x.id===id?"selected":""}>${esc(x.name)}</option>`).join("");$("#fSensorValue").value=s?.value??0;$("#fSensorStatus").value=s?.status||"ONLINE";}
async function submitForm(e){e.preventDefault();const mode=$("#commandForm").dataset.mode;try{msg("Saving…");if(mode==="incident"){const edit=$("#commandForm").dataset.editId;if(edit){await api("/incidents",{method:"PATCH",body:JSON.stringify({id:edit,status:$("#commandForm").dataset.editStatus})});}else await api("/incidents",{method:"POST",body:JSON.stringify({title:$("#fTitle").value,disaster_type:$("#fType").value,severity:$("#fSeverity").value,location:$("#fLocation").value,description:$("#fDescription").value,latitude:$("#fLat").value||null,longitude:$("#fLng").value||null})});}else if(mode==="dispatch")await api("/dispatches",{method:"POST",body:JSON.stringify({mission:$("#fMission").value,destination:$("#fDestination").value,priority:$("#fPriority").value,teamId:$("#fTeam").value,incidentId:$("#fIncident").value||null})});else if(mode==="alert")await api("/alerts",{method:"POST",body:JSON.stringify({title:$("#fAlertTitle").value,disaster_type:$("#fAlertType").value,severity:$("#fAlertSeverity").value,location:$("#fAlertLocation").value,message:$("#fAlertMessage").value,recommended_action:$("#fAlertAction").value})});else await api("/sensors",{method:"PATCH",body:JSON.stringify({id:$("#fSensor").value,value:$("#fSensorValue").value,status:$("#fSensorStatus").value})});msg("Operation recorded successfully.",true);await refresh();setTimeout(closeModal,500);}catch(e){msg(e.message);}}
async function openNotifications(){const d=await api("/notifications");$("#notificationList").innerHTML=d.notifications.length?d.notifications.map(n=>`<article class="notification ${n.read_at?"read":""}" data-note="${n.id}"><b>${esc(n.title)}</b><p>${esc(n.message)}</p><small>${ago(n.created_at)}</small></article>`).join(""):"<div class='empty'>No notifications.</div>";$("#notificationDrawer").classList.add("open");text("#notificationBadge",d.unread||"");$$("[data-note]").forEach(n=>n.onclick=async()=>{await api("/notifications/"+n.dataset.note+"/read",{method:"PATCH"});openNotifications();});}
function assistantAnswer(q){const x=q.toLowerCase();if(x.includes("flood"))return"During a flood: move to higher ground, avoid moving water, do not drive through flooded roads, switch off electricity only if safe, and follow official evacuation instructions.";if(x.includes("earthquake"))return"During an earthquake: drop, cover and hold on. Stay away from windows. If outside, move away from buildings and power lines. Expect aftershocks.";if(x.includes("fire"))return"During a fire: raise the alarm, evacuate immediately, stay low under smoke, never use lifts, and do not re-enter until authorities say it is safe.";if(x.includes("cyclone"))return"During a cyclone: stay indoors away from windows, follow official alerts, evacuate if instructed, and avoid flooded or coastal areas.";if(x.includes("kit")||x.includes("emergency"))return"An emergency kit should include drinking water, food, medicines, first-aid supplies, flashlight, batteries/power bank, important documents, basic clothing and communication supplies.";return"I can provide basic preparedness guidance for floods, earthquakes, fires, cyclones and emergency kits. This guidance is informational and does not replace official emergency authorities.";}
function assistantSend(q){$("#assistantMessages").insertAdjacentHTML("beforeend",`<div class="user">${esc(q)}</div><div class="bot">${esc(assistantAnswer(q))}</div>`);$("#assistantMessages").scrollTop=99999;}
async function refresh(){try{await Promise.all([loadDashboard(),loadIncidents(),loadSensors(),loadTeams(),loadDispatches(),loadRisk(),loadAlerts(),loadReports(),loadActivity(),loadAudit(),loadGuides(),loadContacts(),loadMap()]);}catch(e){console.error(e);}}
$("#newIncidentBtn").onclick=()=>openModal("incident");$("#newDispatchBtn").onclick=()=>openModal("dispatch");$("#newAlertBtn").onclick=()=>openModal("alert");$("#simulateBtn").onclick=()=>openSensorModal(state.sensors[0]?.id);$("#modalClose").onclick=closeModal;$("#cancelModal").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};$("#commandForm").onsubmit=submitForm;$("#refreshBtn").onclick=refresh;$("#logoutBtn").onclick=async()=>{await api("/logout",{method:"POST"});location.href="/login"};$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("mobile-open");$("#notificationBtn").onclick=openNotifications;$("#closeDrawer").onclick=()=>$("#notificationDrawer").classList.remove("open");$("#dismissBanner").onclick=()=>$("#criticalBanner").classList.add("hidden");$("#reportRange").onchange=loadReports;
$$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadMap();});
$("#assistantToggle").onclick=()=>$("#assistant").classList.toggle("open");$("#assistantClose").onclick=()=>$("#assistant").classList.remove("open");$("#assistantForm").onsubmit=e=>{e.preventDefault();const q=$("#assistantInput").value.trim();if(q){assistantSend(q);$("#assistantInput").value=""}};$$(".assistant-suggestions button").forEach(b=>b.onclick=()=>assistantSend(b.dataset.q));
$("#fSensor").onchange=()=>{const s=state.sensors.find(x=>x.id===$("#fSensor").value);if(s)$("#fSensorValue").value=s.value;};
$("#mainNav").addEventListener("click",e=>{const a=e.target.closest("a");if(a&&window.innerWidth<681)$("#sidebar").classList.remove("mobile-open");});
setInterval(()=>{if(document.visibilityState==="visible")refresh();},30000);
(async()=>{if(await loadUser()){try{await refresh();}catch(e){console.error(e);}}})();
